spring:
  application:
    name: questionnaire
  datasource:
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      password: 123

server:
  port: 8081

mybatis:
  mapper-locations: classpath:github/nowsoar/questionnaire/mapper/*.xml
  type-aliases-package: github/nowsoar/questionnaire/entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

logging:
  level:
    github.nowsoar.questionnaire.mapper: debug